---
networks:
  frontend:
    external: true
services:
  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      traefik.enable: true
      traefik.http.routers.whoami.rule: Host(`whoami.hostname.domain.tld`)
      traefik.http.routers.whoami.entrypoints: web
      traefik.http.routers.whoami.service: whoami
      traefik.http.services.whoami.loadbalancer.server.port: 80