---
volumes:
  redis-data:

networks:
  database:
    external: true

services:
  redis: 
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - database
    